app/webadmin/forms.py
from wtforms.validators import DataRequired

from app import db
from flask_wtf import FlaskForm
from wtforms import StringField, widgets
from wtforms_alchemy import (model_form_factory, ModelFormField, QuerySelectMultipleField)
from app.models import *

BaseModelForm = model_form_factory(FlaskForm)


class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session


class PlaceSearchForm(FlaskForm):
    name = StringField('Place name')


class AddressForm(ModelForm):
    class Meta:
        model = Address
        exclude = ['created_at', 'updated_at', 'wkb_geometry']


class CafeForm(ModelForm):
    class Meta:
        model = Cafe
        exclude = ['created_at', 'updated_at']

    address = ModelFormField(AddressForm)
    zones = QuerySelectMultipleField(u'Zone', get_label='zone',
                                     query_factory=lambda: Zone.query.all(),
                                     widget=widgets.ListWidget(prefix_label=False),
                                     option_widget=widgets.CheckboxInput())
    styles = QuerySelectMultipleField(u'Style', get_label='style',
                                      query_factory=lambda: Style.query.all(),
                                      widget=widgets.ListWidget(prefix_label=False),
                                      option_widget=widgets.CheckboxInput())
    activities = QuerySelectMultipleField(u'Activities', get_label='activity',
                                          query_factory=lambda: Activity.query.all(),
                                          widget=widgets.ListWidget(prefix_label=False),
                                          option_widget=widgets.CheckboxInput())


class InstagramPostForm(ModelForm):
    class Meta:
        model = InstagramEmbedded
        only = ['embedded_url', 'official_post']

app/webadmin/__init__.py
from flask import Blueprint

webadmin = Blueprint('webadmin', __name__, url_prefix='/webadmin')

from . import views

app/webadmin/views.py
import os

import googlemaps
from flask import render_template, request, url_for, redirect, flash

from .forms import *
from . import webadmin


gmaps = googlemaps.Client(os.environ.get('GOOGLE_MAP_API_KEY'))


@webadmin.route('/')
def index():
    return render_template('webadmin/index.html')


@webadmin.route('/places/find', methods=['GET', 'POST'])
def find_place():
    form = PlaceSearchForm()
    places = []
    if request.method == 'POST':
        name = form.name.data
        result = gmaps.find_place(name, input_type='textquery')
        for cand in result['candidates']:
            place = gmaps.place(cand['place_id'], language='TH')
            places.append(
                {
                    'place_id': cand['place_id'],
                    'name': place['result']['name'],
                    'formatted_address': place['result']['formatted_address'],
                    'url': place['result']['url']
                }
            )
    return render_template('webadmin/place_search_form.html', form=form, places=places)


@webadmin.route('/cafes/add', methods=['GET', 'POST'])
def add_cafe():
    place_id = request.args.get('place_id')
    form = CafeForm()
    if place_id:
        place = gmaps.place(place_id, language='TH')
        form.name.data = place['result'].get('name')
        try:
            form.address.lat.data, form.address.lon.data = place['result']['geometry']['location'].values()
        except KeyError:
            pass
        for addr_component in place['result'].get('address_components', []):
            if 'route' in addr_component['types']:
                form.address.street.data = addr_component['long_name']
            elif 'sublocality_level_1' in addr_component['types']:
                form.address.district.data = addr_component['long_name']
            elif 'sublocality_level_2' in addr_component['types']:
                form.address.subdistrict.data = addr_component['long_name']
            elif 'administrative_area_level_1' in addr_component['types']:
                form.address.province.data = addr_component['long_name']
            elif 'postal_code' in addr_component['types']:
                form.address.postal_code.data = addr_component['long_name']

    if request.method == 'POST':
        if form.validate_on_submit():
            cafe = Cafe()
            form.populate_obj(cafe)
            if cafe.address.lat and cafe.address.lon:
                cafe.address.add_geometry()
            db.session.add(cafe)
            db.session.commit()
            return redirect(url_for('webadmin.index'))
        else:
            print(form.errors)
    return render_template('webadmin/cafe_add.html', form=form)


@webadmin.route('/cafes/<int:cafe_id>/edit', methods=['GET', 'POST'])
def edit_cafe(cafe_id):
    cafe = Cafe.query.get(cafe_id)
    form = CafeForm(obj=cafe)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(cafe)
            db.session.add(cafe)
            db.session.commit()
            flash('Updated data successfully.', 'success')
        return redirect(url_for('webadmin.list_cafes'))
    return render_template('webadmin/cafe_add.html', form=form)


@webadmin.route('/cafes')
def list_cafes():
    cafes = Cafe.query.all()
    return render_template('webadmin/cafes.html', cafes=cafes)


@webadmin.route('/cafes/<int:cafe_id>/ig-post/add', methods=['GET', 'POST'])
def add_ig_post(cafe_id):
    form = InstagramPostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post = InstagramEmbedded()
            form.populate_obj(post)
            post.cafe_id = cafe_id
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('webadmin.list_cafes'))
    return render_template('webadmin/ig_url_add.html', form=form)


@webadmin.route('/ig-posts/<int:post_id>/edit', methods=['GET', 'POST'])
def edit_ig_post(post_id):
    post = InstagramEmbedded.query.get(post_id)
    form = InstagramPostForm(obj=post)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(post)
            db.session.add(post)
            db.session.commit()
            flash('The post have been updated.', 'success')
            return redirect(url_for('webadmin.list_cafes'))
    return render_template('webadmin/ig_url_add.html', form=form)


@webadmin.route('/ig-posts/<int:post_id>/remove', methods=['GET'])
def remove_ig_post(post_id):
    post = InstagramEmbedded.query.get(post_id)
    if post:
        db.session.delete(post)
        db.session.commit()
        flash('The post has been removed.', 'success')
    return redirect(url_for('webadmin.list_cafes'))

app/templates/webadmin/cafe_add.html
{% extends "base.html" %}

{% block title %}Add/Edit Cafe{% endblock %}

{% block content %}
<section class="section">
    <div class="columns">
        <div class="column is-one-third is-offset-4">
            <div class="container">
                <h1 class="title has-text-centered">Cafe Form</h1>
                <form method="post">
                    {{form.hidden_tag()}}
                    <div class="box">
                        <h2 class="title">General Information</h2>
                        <p class="field">
                            <label class="label">{{form.name.label}}</label>
                        <div class="control">
                            {{form.name(class="input")}}
                        </div>
                        </p>
                        <p class="field">
                            <label class="label">{{form.price_level.label}}</label>
                            <div class="select">
                                {{form.price_level()}}
                            </div>
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Styles</h2>
                        <p class="field">
                            {{form.styles()}}
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Zone Availability</h2>
                        <p class="field">
                            {{form.zones()}}
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Seating</h2>
                        <p class="field">
                            <label class="label">{{form.seating_avail.label}}</label>
                        <div class="select">
                            {{form.seating_avail()}}
                        </div>
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Amenities</h2>
                        <p class="field">
                            <label class="checkbox">
                                {{form.pet_friendly()}}
                                {{form.pet_friendly.label}}
                            </label>
                        </p>
                        <p class="field">
                            <label class="checkbox">
                                {{form.free_wifi()}}
                                {{form.free_wifi.label}}
                            </label>
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Recommended Activities</h2>
                        <p class="field">
                            {{form.activities()}}
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Parking</h2>
                        <p class="field">
                            <label class="label">{{form.parking_avail.label}}</label>
                        <div class="select">
                            {{form.parking_avail()}}
                        </div>
                        </p>
                        <p class="field">
                            <label class="checkbox">
                                {{form.parking_fee()}}
                                {{form.parking_fee.label}}
                            </label>
                        </p>
                        <p class="field">
                            <label class="label">{{form.parking_note.label}}</label>
                            {{form.parking_note(class="textarea")}}
                        </p>
                    </div>
                    <div class="box">
                        <p class="field">
                            <label class="label">{{form.service_charge_rate.label}}</label>
                            <div class="control">
                                {{form.service_charge_rate(class="input")}}
                            </div>
                        </p>
                        <div class="field">
                            <label class="checkbox">
                                {{form.vat_included()}}
                                {{form.vat_included.label}}
                                <p class="help is-info">
                                    {{form.vat_included.description}}
                                </p>
                            </label>
                        </div>
                    </div>
                    <div class="box">
                        <h2 class="title">Address</h2>
                        {{form.address.hidden_tag()}}
                        <p class="field">
                            <label class="label">{{form.address.street.label}}</label>
                            <div class="control">
                                {{form.address.street(class="input")}}
                            </div>
                        </p>
                        <p class="field">
                            <label class="label">{{form.address.subdistrict.label}}</label>
                            <div class="control">
                                {{form.address.subdistrict(class="input")}}
                            </div>
                        </p>
                        <p class="field">
                            <label class="label">{{form.address.district.label}}</label>
                            <div class="control">
                                {{form.address.district(class="input")}}
                            </div>
                        </p>
                        <p class="field">
                            <label class="label">{{form.address.province.label}}</label>
                            <div class="control">
                                {{form.address.province(class="input")}}
                            </div>
                        </p>
                        <p class="field">
                            <label class="label">{{form.address.postal_code.label}}</label>
                            <div class="control">
                                {{form.address.postal_code(class="input")}}
                            </div>
                        </p>
                    </div>
                    <div class="box">
                        <h2 class="title">Geolocation</h2>
                        <p class="field">
                            <label class="label">{{form.address.lat.label}}</label>
                            <div class="control">
                                {{form.address.lat(class="input")}}
                            </div>
                        </p>
                        <p class="field">
                            <label class="label">{{form.address.lon.label}}</label>
                            <div class="control">
                                {{form.address.lon(class="input")}}
                            </div>
                        </p>
                    </div>
                    <div class="field">
                        <div class="control">
                            <div class="buttons is-centered">
                                <a class="button is-light" href="{{url_for('webadmin.index')}}">Back</a>
                                <input class="button is-success" type="submit" value="Submit">
                            </div>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</section>
{% endblock %}

app/templates/webadmin/cafe_edit.html
{% extends "base.html" %}

{% block title %}Add/Edit Cafe{% endblock %}

{% block content %}
<h1>Cafe Form</h1>
<form method="post">
    {{form.hidden_tag()}}
    <p>
        <label>{{form.name.label}}</label>
        {{form.name()}}
    </p>
    <h2>Address</h2>
    {{form.address.hidden_tag()}}
    <p>
        <label>{{form.address.street.label}}</label>
        {{form.address.street()}}
    </p>
    <p>
        <label>{{form.address.district.label}}</label>
        {{form.address.district()}}
    </p>
    <p>
        <label>{{form.address.province.label}}</label>
        {{form.address.province()}}
    </p>
    <a href="{{url_for('webadmin.index')}}">Back</a>
    <input type="submit" value="Submit">
</form>
{% endblock %}

app/templates/webadmin/cafes.html
{% extends "base.html" %}

{% block style %}
{{super()}}
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">All Cafes</h1>
        <table class="table is-fullwidth">
            {% for cafe in cafes %}
            <tr>
                <td>Name</td>
                <td>{{cafe.name}}</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>{{cafe.address}}</td>
            </tr>
            <tr>
                <td>Geolocation</td>
                <td>
                    {{cafe.address.location}}
                </td>
            </tr>
            <tr>
                <td>Instagram Posts</td>
                <td>
                    <table>
                        {% for post in cafe.ig_posts %}
                        <tr>
                            <td>
                                {{post|safe}}
                                <a href="{{url_for('webadmin.edit_ig_post', post_id=post.id)}}" class="button is-info">
                                    <span class="icon">
                                        <i class="fa-solid fa-pencil"></i>
                                    </span>
                                    <span>Edit</span>
                                </a>
                                <a href="{{url_for('webadmin.remove_ig_post', post_id=post.id)}}" class="button is-danger">
                                    <span class="icon">
                                        <i class="fa-solid fa-trash-can"></i>
                                    </span>
                                    <span>Remove</span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td>
                                <a class="button is-outlined is-success" href="{{url_for('webadmin.add_ig_post', cafe_id=cafe.id)}}">
                                    <span class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </span>
                                    <span>Add</span>
                                </a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <a href="{{url_for('webadmin.edit_cafe', cafe_id=cafe.id)}}" class="button is-outlined is-info">
                        <span class="icon">
                            <i class="fa-solid fa-pen"></i>
                        </span>
                            <span>
                            Edit
                        </span>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
        <a href="{{url_for('webadmin.index')}}" class="button is-text">Back</a>

    </div>
</section>

{% endblock %}

app/templates/webadmin/ig_url_add.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Instagram Post Form</h1>
        <div class="columns">
            <div class="column">
                <div class="box">
                    <form method="post">
                        {{form.hidden_tag()}}
                        <p class="field">
                            <label class="label">{{form.embedded_url.label}}</label>
                            {{form.embedded_url(class="textarea")}}
                        </p>
                        <p class="field">
                            <label class="checkbox">
                                {{form.official_post()}}
                                {{form.official_post.label}}
                            </label>
                        </p>
                        <div class="field">
                            <div class="control">
                                <a href="{{url_for('webadmin.index')}}" class="button is-light">Back</a>
                                <input class="button is-success" type="submit" value="submit">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/webadmin/index.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Web Admin</h1>
        <h1 class="subtitle">Select the Menu</h1>
        <ul>
            <li><a href="{{url_for('webadmin.find_place')}}">Find a place</a></li>
            <li><a href="{{url_for('webadmin.add_cafe')}}">Add a place</a></li>
            <li><a href="{{url_for('webadmin.list_cafes')}}">List all places</a></li>
        </ul>
    </div>
</section>

{% endblock %}

app/templates/webadmin/place_search_form.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-two-thirds is-offset-2">
                <h1 class="title has-text-centered">Find Place</h1>
                {% if places %}
                <h3 class="subtitle has-text-centered">Search Results</h3>
                <table class="table">
                    <th>Name</th>
                    <th>Address</th>
                    <th>Map</th>
                    <th>Action</th>
                    {% for p in places %}
                    <tr>
                        <td>{{p.name}}</td>
                        <td>{{p.formatted_address}}</td>
                        <td><a href="{{p.url}}">See a map</a></td>
                        <td><a href="{{url_for('webadmin.add_cafe', place_id=p.place_id)}}">Choose</a></td>
                    </tr>
                    {% endfor %}
                </table>
                {% endif %}
                <div class="box">
                    <form method="post">
                        {{form.hidden_tag()}}
                        <div class="field">
                            <label class="label">{{form.name.label}}</label>
                            {{form.name(class="input", placeholder="e.g. Herringbone Bangkok")}}
                            <p class="help is-info">Add city or country to narrow down the search.</p>
                        </div>
                        <a class="button is-light" href="{{url_for('webadmin.index')}}">Back</a>
                        <input class="button is-success is-outlined" type="submit" value="Submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}